import React, { createContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

interface LanguageProviderProps {
  children: ReactNode;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.expenses': 'Expenses',
    'nav.scan': 'Scan',
    'nav.category': 'Category',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.edit': 'Edit',
    'common.done': 'Done',
    
    // Home Screen
    'home.welcomeBack': 'Welcome back,',
    'home.totalSales': 'Total Sales',
    'home.netSales': 'Net Sales',
    'home.grossSales': 'Gross Sales',
    'home.totalSpent': 'Total Spent',
    'home.netProfit': 'Net Profit',
    'home.profitMargin': 'Profit Margin',
    'home.thisMonth': 'This Month',
    'home.expenses': 'expenses',
    'home.captured': 'captured',
    'home.unmatched': 'unmatched',
    'home.needsAttention': 'Needs Attention',
    'home.newExpense': 'New Expense',
    'home.newStatement': 'New Statement',
    'home.statements': 'Statements',
    'home.statementsSubtitle': 'View all financial statements',
    'home.recurring': 'Recurring',
    'home.recurringSubtitle': 'Manage recurring expenses',
    'home.salesReport': 'Sales Report',
    'home.salesReportSubtitle': 'View sales analytics',
    'home.roles': 'Roles',
    'home.recentActivity': 'Recent Activity',
    'home.viewAll': 'View All',
    'home.receiptTracking': 'Receipt Tracking',
    'home.matched': 'Matched',
    'home.unmatchedLabel': 'Unmatched',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'PROFILE',
    'settings.accountInfo': 'Account Information',
    'settings.businessDetails': 'Business Details',
    'settings.preferences': 'PREFERENCES',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.categories': 'Categories',
    'settings.data': 'DATA',
    'settings.exportData': 'Export Data',
    'settings.support': 'SUPPORT',
    'settings.contactSupport': 'Contact Support',
    'settings.rateApp': 'Rate App',
    'settings.legal': 'LEGAL',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.terms': 'Terms & Conditions',
    'settings.signOut': 'Sign Out',
    'settings.version': 'Version 1.0.0',
    
    // Categories
    'categories.infoText': 'Manage which expense categories are available when creating expenses',
    'categories.miscellaneous': 'Miscellaneous',
    'categories.labor': 'Labor',
    'categories.inventory': 'Inventory',
    'categories.operations': 'Operations',
    'categories.tax': 'Tax',
    'categories.transportation': 'Transportation',
    
    // Category Screen
    'category.title': 'Monthly Report',
    'category.subtitle': 'Expense Breakdown',
    'category.compare': 'Compare',
    'category.totalExpenses': 'Total Expenses',
    'category.avgPerTransaction': 'Avg Per Transaction',
    'category.transactions': 'transactions',
    
    // Expenses Screen
    'expenses.title': 'Expenses',
    'expenses.subtitle': 'Track your spending',
    'expenses.search': 'Search expenses...',
    'expenses.allCategories': 'All Categories',
    
    // Expense Details
    'details.title': 'Expense Details',
    'details.receipt': 'Receipt',
    'details.noReceipt': 'No receipt attached',
    'details.uploadReceipt': 'Upload Receipt',
    'details.editExpense': 'Edit Expense',
    'details.deleteExpense': 'Delete Expense',
    'details.deleteConfirm': 'Are you sure you want to delete this expense?',
    'details.editTitle': 'Edit Expense',
    'details.vendor': 'Vendor',
    'details.amount': 'Amount',
    'details.date': 'Date',
    'details.category': 'Category',
    'details.description': 'Description',
    'details.notes': 'Notes',
    
    // New Expense Screen
    'newExpense.title': 'New Expense',
    'newExpense.vendor': 'Vendor',
    'newExpense.vendorPlaceholder': 'Enter vendor name',
    'newExpense.amount': 'Amount',
    'newExpense.amountPlaceholder': 'Enter amount',
    'newExpense.category': 'Category',
    'newExpense.selectCategory': 'Select Category',
    'newExpense.date': 'Date',
    'newExpense.notes': 'Notes',
    'newExpense.notesPlaceholder': 'Add notes (optional)',
    'newExpense.receipt': 'Receipt',
    'newExpense.uploadReceipt': 'Upload Receipt',
    'newExpense.takePhoto': 'Take Photo',
    'newExpense.chooseFromLibrary': 'Choose from Library',
    'newExpense.save': 'Save Expense',
    
    // Statements Screen
    'statements.title': 'Statements',
    'statements.matched': 'matched',
    'statements.processed': 'Processed',
    'statements.processing': 'Processing...',
    'statements.error': 'Error',
    
    // Upload Statement Screen
    'uploadStatement.title': 'Upload Statement',
    'uploadStatement.infoText': 'Upload your bank or credit card statement to automatically match transactions with receipts.',
    'uploadStatement.supportedFormats': 'Supported Formats',
    'uploadStatement.pdfStatements': 'PDF statements',
    'uploadStatement.csvExcel': 'CSV/Excel files',
    'uploadStatement.qfxOfx': 'QFX/OFX files',
    'uploadStatement.selectFile': 'Select Statement File',
    'uploadStatement.changeFile': 'Change File',
    'uploadStatement.tapToBrowse': 'Tap to browse your device',
    'uploadStatement.upload': 'Upload Statement',
    'uploadStatement.uploaded': 'uploaded',
    'uploadStatement.noFileSelected': 'No File Selected',
    'uploadStatement.selectFirst': 'Please select a statement file first',
    'uploadStatement.success': 'Success',
    'uploadStatement.successMessage': 'Statement uploaded successfully',
    'uploadStatement.error': 'Error',
    'uploadStatement.errorMessage': 'Failed to pick file',
    
    // Needs Attention Screen
    'needsAttention.title': 'Needs Attention',
    'needsAttention.subtitle': 'Items requiring review',
    'needsAttention.all': 'All',
    'needsAttention.totalIssues': 'Total Issues',
    'needsAttention.missingReceipts': 'Missing Receipts',
    'needsAttention.unmatched': 'Unmatched',
    'needsAttention.duplicates': 'Duplicates',
    'needsAttention.review': 'Review',
    'needsAttention.dismiss': 'Dismiss',
    'needsAttention.resolve': 'Resolve',
    
    // Alert Detail Screen
    'alertDetail.title': 'Alert Details',
    'alertDetail.resolve': 'Resolve',
    'alertDetail.dismiss': 'Dismiss',
    'alertDetail.uploadReceipt': 'Upload Receipt',
    'alertDetail.scan': 'Scan',
    'alertDetail.chooseFromLibrary': 'Choose from Library',
    'alertDetail.uploadFromFiles': 'Upload from Files',
    'alertDetail.permissionRequired': 'Permission Required',
    'alertDetail.photoLibraryPermission': 'Photo library permission is required',
    'alertDetail.missingReceipt': 'Missing Receipt',
    'alertDetail.unmatchedReceipt': 'Unmatched Receipt',
    'alertDetail.duplicate': 'Duplicate',
    'alertDetail.review': 'Review',
    'alertDetail.uncategorized': 'Uncategorized',
    'alertDetail.issue': 'Issue',
    'alertDetail.suggestedActions': 'Suggested Actions',
    'alertDetail.linkToStatement': 'Link to Statement Charge',
    'alertDetail.mergeTransactions': 'Merge Transactions',
    'alertDetail.deleteDuplicate': 'Delete Duplicate',
    'alertDetail.matchToTransaction': 'Match to Transaction',
    'alertDetail.reviewTransaction': 'Review Transaction',
    'alertDetail.reviewDetails': 'Review Details',
    'alertDetail.cancel': 'Cancel',
    
    // Recurring Screen
    'recurring.title': 'Recurring Expenses',
    'recurring.subtitle': 'Manage subscriptions',
    'recurring.active': 'Active',
    'recurring.paused': 'Paused',
    'recurring.monthly': 'Monthly',
    'recurring.yearly': 'Yearly',
    'recurring.weekly': 'Weekly',
    
    // Sales Report Screen
    'salesReport.title': 'Sales Report',
    'salesReport.subtitle': 'Revenue analytics',
    
    // Scan Screen
    'scan.title': 'Scan Receipt',
    'scan.capture': 'Capture',
    'scan.retake': 'Retake',
    'scan.save': 'Save',
    
    // Account Info Screen
    'accountInfo.title': 'Account Information',
    'accountInfo.changePhoto': 'Change Photo',
    'accountInfo.fullName': 'Full Name',
    'accountInfo.email': 'Email',
    'accountInfo.phoneNumber': 'Phone Number',
    'accountInfo.enterName': 'Enter your name',
    'accountInfo.enterEmail': 'Enter your email',
    'accountInfo.enterPhone': 'Enter your phone number',
    'accountInfo.saveChanges': 'Save Changes',
    
    // Appearance Screen
    'appearance.title': 'Appearance',
    'appearance.theme': 'Theme',
    'appearance.light': 'Light',
    'appearance.lightDesc': 'Always use light theme',
    'appearance.dark': 'Dark',
    'appearance.darkDesc': 'Always use dark theme',
    'appearance.auto': 'Auto',
    'appearance.autoDesc': 'Match system theme',
    
    // Business Details Screen
    'businessDetails.title': 'Business Details',
    'businessDetails.businessName': 'Business Name',
    'businessDetails.taxId': 'Tax ID / EIN',
    'businessDetails.address': 'Business Address',
    'businessDetails.industry': 'Industry',
    'businessDetails.enterBusinessName': 'Enter business name',
    'businessDetails.enterTaxId': 'Enter tax ID',
    'businessDetails.enterAddress': 'Enter business address',
    'businessDetails.enterIndustry': 'Enter industry',
    'businessDetails.saveChanges': 'Save Changes',
    
    // Contact Support Screen
    'contactSupport.title': 'Contact Support',
    'contactSupport.email': 'Email',
    'contactSupport.liveChat': 'Live Chat',
    'contactSupport.available': 'Available 9am-5pm EST',
    'contactSupport.sendMessage': 'Send us a message',
    'contactSupport.subject': 'Subject',
    'contactSupport.message': 'Message',
    'contactSupport.subjectPlaceholder': 'What can we help you with?',
    'contactSupport.messagePlaceholder': 'Describe your issue or question...',
    'contactSupport.submit': 'Send Message',
    'contactSupport.missingInfo': 'Missing Information',
    'contactSupport.fillAllFields': 'Please fill in all fields',
    'contactSupport.messageSent': 'Message Sent',
    'contactSupport.responseTime': 'Our support team will get back to you within 24 hours',
    
    // Rate App Screen
    'rateApp.title': 'Rate Our App',
    'rateApp.enjoying': 'Enjoying Tally?',
    'rateApp.feedbackHelps': 'Your feedback helps us improve and serve you better',
    'rateApp.amazing': 'Amazing!',
    'rateApp.great': 'Great!',
    'rateApp.good': 'Good',
    'rateApp.fair': 'Fair',
    'rateApp.poor': 'Poor',
    'rateApp.helpGrow': 'Help us grow',
    'rateApp.supportDevelopment': 'Support development',
    'rateApp.shareExperience': 'Share your experience',
    'rateApp.thankYou': 'Thank You!',
    'rateApp.rateAppStore': 'Would you like to rate us on the App Store?',
    'rateApp.notNow': 'Not Now',
    'rateApp.rateButton': 'Rate on App Store',
    'rateApp.feedback': 'Feedback',
    'rateApp.notSatisfied': "We're sorry you're not satisfied. Would you like to contact support?",
    'rateApp.contactSupport': 'Contact Support',
    'rateApp.success': 'Success',
    'rateApp.thanksSupport': 'Thanks for your support!',
    
    // Roles Screen
    'roles.title': 'Roles',
    'roles.noMembersYet': 'No members yet',
    'roles.emptySubtitle': 'Add admins or employees to manage access for this organization.',
    'roles.admin': 'Admin',
    'roles.employee': 'Employee',
    'roles.created': 'Created',
    'roles.addMember': 'Add Member',
    'roles.editEmployee': 'Edit employee',
    'roles.deleteMember': 'Delete Member?',
    'roles.deleteConfirm': 'Are you sure you want to delete this member? This action cannot be undone.',
    'roles.name': 'Name',
    'roles.email': 'Email',
    'roles.role': 'Role',
    'roles.employeeNamePlaceholder': 'Employee name',
    'roles.emailPlaceholder': 'employee@company.com',
    'roles.addMemberButton': 'Add member',
    'roles.save': 'Save',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.expenses': 'Gastos',
    'nav.scan': 'Escanear',
    'nav.category': 'Categoría',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.back': 'Atrás',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    'common.edit': 'Editar',
    'common.done': 'Hecho',
    
    // Home Screen
    'home.welcomeBack': 'Bienvenido de nuevo,',
    'home.totalSales': 'Ventas Totales',
    'home.netSales': 'Ventas Netas',
    'home.grossSales': 'Ventas Brutas',
    'home.totalSpent': 'Total Gastado',
    'home.netProfit': 'Beneficio Neto',
    'home.profitMargin': 'Margen de Beneficio',
    'home.thisMonth': 'Este Mes',
    'home.expenses': 'gastos',
    'home.captured': 'capturados',
    'home.unmatched': 'sin coincidencia',
    'home.needsAttention': 'Requiere Atención',
    'home.newExpense': 'Nuevo Gasto',
    'home.newStatement': 'Nuevo Estado',
    'home.statements': 'Estados',
    'home.statementsSubtitle': 'Ver todos los estados financieros',
    'home.recurring': 'Recurrentes',
    'home.recurringSubtitle': 'Gestionar gastos recurrentes',
    'home.salesReport': 'Informe de Ventas',
    'home.salesReportSubtitle': 'Ver análisis de ventas',
    'home.roles': 'Roles',
    'home.recentActivity': 'Actividad Reciente',
    'home.viewAll': 'Ver Todo',
    'home.receiptTracking': 'Seguimiento de Recibos',
    'home.matched': 'Coincidentes',
    'home.unmatchedLabel': 'Sin Coincidencia',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.profile': 'PERFIL',
    'settings.accountInfo': 'Información de Cuenta',
    'settings.businessDetails': 'Detalles de Negocio',
    'settings.preferences': 'PREFERENCIAS',
    'settings.appearance': 'Apariencia',
    'settings.language': 'Idioma',
    'settings.categories': 'Categorías',
    'settings.data': 'DATOS',
    'settings.exportData': 'Exportar Datos',
    'settings.support': 'SOPORTE',
    'settings.contactSupport': 'Contactar Soporte',
    'settings.rateApp': 'Calificar App',
    'settings.legal': 'LEGAL',
    'settings.privacyPolicy': 'Política de Privacidad',
    'settings.terms': 'Términos y Condiciones',
    'settings.signOut': 'Cerrar Sesión',
    'settings.version': 'Versión 1.0.0',
    
    // Categories
    'categories.infoText': 'Administre qué categorías de gastos están disponibles al crear gastos',
    'categories.miscellaneous': 'Misceláneo',
    'categories.labor': 'Mano de Obra',
    'categories.inventory': 'Inventario',
    'categories.operations': 'Operaciones',
    'categories.tax': 'Impuestos',
    'categories.transportation': 'Transporte',
    
    // Category Screen
    'category.title': 'Informe Mensual',
    'category.subtitle': 'Desglose de Gastos',
    'category.compare': 'Comparar',
    'category.totalExpenses': 'Gastos Totales',
    'category.avgPerTransaction': 'Promedio por Transacción',
    'category.transactions': 'transacciones',
    
    // Expenses Screen
    'expenses.title': 'Gastos',
    'expenses.subtitle': 'Seguimiento de gastos',
    'expenses.search': 'Buscar gastos...',
    'expenses.allCategories': 'Todas las Categorías',
    
    // Expense Details
    'details.title': 'Detalles del Gasto',
    'details.receipt': 'Recibo',
    'details.noReceipt': 'Sin recibo adjunto',
    'details.uploadReceipt': 'Subir Recibo',
    'details.editExpense': 'Editar Gasto',
    'details.deleteExpense': 'Eliminar Gasto',
    'details.deleteConfirm': '¿Estás seguro de eliminar este gasto?',
    'details.editTitle': 'Editar Gasto',
    'details.vendor': 'Proveedor',
    'details.amount': 'Monto',
    'details.date': 'Fecha',
    'details.category': 'Categoría',
    'details.description': 'Descripción',
    'details.notes': 'Notas',
    
    // New Expense Screen
    'newExpense.title': 'Nuevo Gasto',
    'newExpense.vendor': 'Proveedor',
    'newExpense.vendorPlaceholder': 'Ingrese el nombre del proveedor',
    'newExpense.amount': 'Monto',
    'newExpense.amountPlaceholder': 'Ingrese el monto',
    'newExpense.category': 'Categoría',
    'newExpense.selectCategory': 'Seleccionar Categoría',
    'newExpense.date': 'Fecha',
    'newExpense.notes': 'Notas',
    'newExpense.notesPlaceholder': 'Agregar notas (opcional)',
    'newExpense.receipt': 'Recibo',
    'newExpense.uploadReceipt': 'Subir Recibo',
    'newExpense.takePhoto': 'Tomar Foto',
    'newExpense.chooseFromLibrary': 'Elegir de la Biblioteca',
    'newExpense.save': 'Guardar Gasto',
    
    // Statements Screen
    'statements.title': 'Estados',
    'statements.matched': 'coincidentes',
    'statements.processed': 'Procesado',
    'statements.processing': 'Procesando...',
    'statements.error': 'Error',
    
    // Upload Statement Screen
    'uploadStatement.title': 'Subir Estado',
    'uploadStatement.infoText': 'Sube tu estado de cuenta bancario o de tarjeta de crédito para emparejar automáticamente las transacciones con los recibos.',
    'uploadStatement.supportedFormats': 'Formatos Admitidos',
    'uploadStatement.pdfStatements': 'Estados en PDF',
    'uploadStatement.csvExcel': 'Archivos CSV/Excel',
    'uploadStatement.qfxOfx': 'Archivos QFX/OFX',
    'uploadStatement.selectFile': 'Seleccionar Archivo de Estado',
    'uploadStatement.changeFile': 'Cambiar Archivo',
    'uploadStatement.tapToBrowse': 'Toca para navegar en tu dispositivo',
    'uploadStatement.upload': 'Subir Estado',
    'uploadStatement.uploaded': 'subido',
    'uploadStatement.noFileSelected': 'Ningún Archivo Seleccionado',
    'uploadStatement.selectFirst': 'Por favor selecciona primero un archivo de estado',
    'uploadStatement.success': 'Éxito',
    'uploadStatement.successMessage': 'Estado subido exitosamente',
    'uploadStatement.error': 'Error',
    'uploadStatement.errorMessage': 'Error al seleccionar archivo',
    
    // Needs Attention Screen
    'needsAttention.title': 'Requiere Atención',
    'needsAttention.subtitle': 'Elementos que requieren revisión',
    'needsAttention.all': 'Todos',    'needsAttention.totalIssues': 'Problemas Totales',    'needsAttention.missingReceipts': 'Recibos Faltantes',
    'needsAttention.unmatched': 'Sin Coincidencia',
    'needsAttention.duplicates': 'Duplicados',
    'needsAttention.review': 'Revisar',
    'needsAttention.dismiss': 'Descartar',
    'needsAttention.resolve': 'Resolver',
    
    // Alert Detail Screen
    'alertDetail.title': 'Detalles de Alerta',
    'alertDetail.resolve': 'Resolver',
    'alertDetail.dismiss': 'Descartar',
    'alertDetail.uploadReceipt': 'Subir Recibo',
    'alertDetail.scan': 'Escanear',
    'alertDetail.chooseFromLibrary': 'Elegir de la Biblioteca',
    'alertDetail.uploadFromFiles': 'Subir desde Archivos',
    'alertDetail.permissionRequired': 'Permiso Requerido',
    'alertDetail.photoLibraryPermission': 'Se requiere permiso de la biblioteca de fotos',    'alertDetail.missingReceipt': 'Recibo Faltante',
    'alertDetail.unmatchedReceipt': 'Recibo Sin Coincidir',
    'alertDetail.duplicate': 'Duplicado',
    'alertDetail.review': 'Revisar',
    'alertDetail.uncategorized': 'Sin Categoría',
    'alertDetail.issue': 'Problema',
    'alertDetail.suggestedActions': 'Acciones Sugeridas',
    'alertDetail.linkToStatement': 'Vincular a Cargo del Estado',
    'alertDetail.mergeTransactions': 'Fusionar Transacciones',
    'alertDetail.deleteDuplicate': 'Eliminar Duplicado',
    'alertDetail.matchToTransaction': 'Coincidir con Transacción',
    'alertDetail.reviewTransaction': 'Revisar Transacción',
    'alertDetail.reviewDetails': 'Revisar Detalles',
    'alertDetail.cancel': 'Cancelar',    
    // Recurring Screen
    'recurring.title': 'Gastos Recurrentes',
    'recurring.subtitle': 'Gestionar suscripciones',
    'recurring.active': 'Activo',
    'recurring.paused': 'Pausado',
    'recurring.monthly': 'Mensual',
    'recurring.yearly': 'Anual',
    'recurring.weekly': 'Semanal',
    
    // Sales Report Screen
    'salesReport.title': 'Informe de Ventas',
    'salesReport.subtitle': 'Análisis de ingresos',
    
    // Scan Screen
    'scan.title': 'Escanear Recibo',
    'scan.capture': 'Capturar',
    'scan.retake': 'Volver a Tomar',
    'scan.save': 'Guardar',
    
    // Roles Screen
    'roles.title': 'Roles',
    'roles.noMembersYet': 'Sin miembros todavía',
    'roles.emptySubtitle': 'Añade administradores o empleados para gestionar el acceso a esta organización.',
    'roles.admin': 'Administrador',
    'roles.employee': 'Empleado',
    'roles.created': 'Creado',
    'roles.addMember': 'Añadir Miembro',
    'roles.editEmployee': 'Editar empleado',
    'roles.deleteMember': '¿Eliminar Miembro?',
    'roles.deleteConfirm': '¿Estás seguro de que quieres eliminar este miembro? Esta acción no se puede deshacer.',
    'roles.name': 'Nombre',
    'roles.email': 'Correo electrónico',
    'roles.role': 'Rol',
    'roles.employeeNamePlaceholder': 'Nombre del empleado',
    'roles.emailPlaceholder': 'empleado@empresa.com',
    'roles.addMemberButton': 'Añadir miembro',
    'roles.save': 'Guardar',
  },
  zh: {
    // Navigation
    'nav.home': '主页',
    'nav.expenses': '支出',
    'nav.scan': '扫描',
    'nav.category': '类别',
    
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.back': '返回',
    'common.close': '关闭',
    'common.confirm': '确认',
    'common.edit': '编辑',
    'common.done': '完成',
    
    // Home Screen
    'home.welcomeBack': '欢迎回来，',
    'home.totalSales': '总销售额',
    'home.netSales': '净销售额',
    'home.grossSales': '总销售额',
    'home.totalSpent': '总支出',
    'home.netProfit': '净利润',
    'home.profitMargin': '利润率',
    'home.thisMonth': '本月',
    'home.expenses': '支出',
    'home.captured': '已捕获',
    'home.unmatched': '未匹配',
    'home.needsAttention': '需要关注',
    'home.newExpense': '新支出',
    'home.newStatement': '新报表',
    'home.statements': '报表',
    'home.statementsSubtitle': '查看所有财务报表',
    'home.recurring': '定期支出',
    'home.recurringSubtitle': '管理定期支出',
    'home.salesReport': '销售报告',
    'home.salesReportSubtitle': '查看销售分析',
    'home.roles': '角色',
    'home.recentActivity': '最近活动',
    'home.viewAll': '查看全部',
    'home.receiptTracking': '收据跟踪',
    'home.matched': '已匹配',
    'home.unmatchedLabel': '未匹配',
    
    // Settings
    'settings.title': '设置',
    'settings.profile': '个人资料',
    'settings.accountInfo': '账户信息',
    'settings.businessDetails': '业务详情',
    'settings.preferences': '偏好设置',
    'settings.appearance': '外观',
    'settings.language': '语言',
    'settings.categories': '类别',
    'settings.data': '数据',
    'settings.exportData': '导出数据',
    'settings.support': '支持',
    'settings.contactSupport': '联系支持',
    'settings.rateApp': '评价应用',
    'settings.legal': '法律',
    'settings.privacyPolicy': '隐私政策',
    'settings.terms': '条款和条件',
    'settings.signOut': '退出登录',
    'settings.version': '版本 1.0.0',
    
    // Categories
    'categories.infoText': '管理创建费用时可用的费用类别',
    'categories.miscellaneous': '杂项',
    'categories.labor': '人工',
    'categories.inventory': '库存',
    'categories.operations': '运营',
    'categories.tax': '税费',
    'categories.transportation': '运输',
    
    // Category Screen
    'category.title': '月度报告',
    'category.subtitle': '支出明细',
    'category.compare': '对比',
    'category.totalExpenses': '总支出',
    'category.avgPerTransaction': '平均每笔交易',
    'category.transactions': '笔交易',
    
    // Expenses Screen
    'expenses.title': '支出',
    'expenses.subtitle': '追踪您的支出',
    'expenses.search': '搜索支出...',
    'expenses.allCategories': '所有类别',
    
    // Expense Details
    'details.title': '支出详情',
    'details.receipt': '收据',
    'details.noReceipt': '无附件收据',
    'details.uploadReceipt': '上传收据',
    'details.editExpense': '编辑支出',
    'details.deleteExpense': '删除支出',
    'details.deleteConfirm': '确定要删除此支出吗？',
    'details.editTitle': '编辑支出',
    'details.vendor': '商家',
    'details.amount': '金额',
    'details.date': '日期',
    'details.category': '类别',
    'details.description': '描述',
    'details.notes': '备注',
    
    // New Expense Screen
    'newExpense.title': '新支出',
    'newExpense.vendor': '商家',
    'newExpense.vendorPlaceholder': '输入商家名称',
    'newExpense.amount': '金额',
    'newExpense.amountPlaceholder': '输入金额',
    'newExpense.category': '类别',
    'newExpense.selectCategory': '选择类别',
    'newExpense.date': '日期',
    'newExpense.notes': '备注',
    'newExpense.notesPlaceholder': '添加备注（可选）',
    'newExpense.receipt': '收据',
    'newExpense.uploadReceipt': '上传收据',
    'newExpense.takePhoto': '拍照',
    'newExpense.chooseFromLibrary': '从相册选择',
    'newExpense.save': '保存支出',
    
    // Statements Screen
    'statements.title': '报表',
    'statements.matched': '已匹配',
    'statements.processed': '已处理',
    'statements.processing': '处理中...',
    'statements.error': '错误',
    
    // Upload Statement Screen
    'uploadStatement.title': '上传报表',
    'uploadStatement.infoText': '上传您的银行或信用卡报表以自动匹配交易和收据。',
    'uploadStatement.supportedFormats': '支持的格式',
    'uploadStatement.pdfStatements': 'PDF报表',
    'uploadStatement.csvExcel': 'CSV/Excel文件',
    'uploadStatement.qfxOfx': 'QFX/OFX文件',
    'uploadStatement.selectFile': '选择报表文件',
    'uploadStatement.changeFile': '更换文件',
    'uploadStatement.tapToBrowse': '点击浏览您的设备',
    'uploadStatement.upload': '上传报表',
    'uploadStatement.uploaded': '已上传',
    'uploadStatement.noFileSelected': '未选择文件',
    'uploadStatement.selectFirst': '请先选择一个报表文件',
    'uploadStatement.success': '成功',
    'uploadStatement.successMessage': '报表上传成功',
    'uploadStatement.error': '错误',
    'uploadStatement.errorMessage': '文件选择失败',
    
    // Needs Attention Screen
    'needsAttention.title': '需要关注',
    'needsAttention.subtitle': '需要审核的项目',
    'needsAttention.all': '全部',    'needsAttention.totalIssues': '总问题',    'needsAttention.missingReceipts': '缺少收据',
    'needsAttention.unmatched': '未匹配',
    'needsAttention.duplicates': '重复',
    'needsAttention.review': '审核',
    'needsAttention.dismiss': '忽略',
    'needsAttention.resolve': '解决',
    
    // Alert Detail Screen
    'alertDetail.title': '警报详情',
    'alertDetail.resolve': '解决',
    'alertDetail.dismiss': '忽略',
    'alertDetail.uploadReceipt': '上传收据',
    'alertDetail.scan': '扫描',
    'alertDetail.chooseFromLibrary': '从相册选择',
    'alertDetail.uploadFromFiles': '从文件上传',
    'alertDetail.permissionRequired': '需要权限',
    'alertDetail.photoLibraryPermission': '需要相册权限',    'alertDetail.missingReceipt': '缺少收据',
    'alertDetail.unmatchedReceipt': '未匹配收据',
    'alertDetail.duplicate': '重复',
    'alertDetail.review': '审核',
    'alertDetail.uncategorized': '未分类',
    'alertDetail.issue': '问题',
    'alertDetail.suggestedActions': '建议操作',
    'alertDetail.linkToStatement': '链接到账单费用',
    'alertDetail.mergeTransactions': '合并交易',
    'alertDetail.deleteDuplicate': '删除重复',
    'alertDetail.matchToTransaction': '匹配到交易',
    'alertDetail.reviewTransaction': '审核交易',
    'alertDetail.reviewDetails': '审核详情',
    'alertDetail.cancel': '取消',    
    // Recurring Screen
    'recurring.title': '定期支出',
    'recurring.subtitle': '管理订阅',
    'recurring.active': '活跃',
    'recurring.paused': '暂停',
    'recurring.monthly': '每月',
    'recurring.yearly': '每年',
    'recurring.weekly': '每周',
    
    // Sales Report Screen
    'salesReport.title': '销售报告',
    'salesReport.subtitle': '收入分析',
    
    // Scan Screen
    'scan.title': '扫描收据',
    'scan.capture': '捕获',
    'scan.retake': '重拍',
    'scan.save': '保存',
    
    // Account Info Screen
    'accountInfo.title': '账户信息',
    'accountInfo.changePhoto': '更换照片',
    'accountInfo.fullName': '全名',
    'accountInfo.email': '电子邮件',
    'accountInfo.phoneNumber': '电话号码',
    'accountInfo.enterName': '输入您的姓名',
    'accountInfo.enterEmail': '输入您的电子邮件',
    'accountInfo.enterPhone': '输入您的电话号码',
    'accountInfo.saveChanges': '保存更改',
    
    // Appearance Screen
    'appearance.title': '外观',
    'appearance.theme': '主题',
    'appearance.light': '浅色',
    'appearance.lightDesc': '始终使用浅色主题',
    'appearance.dark': '深色',
    'appearance.darkDesc': '始终使用深色主题',
    'appearance.auto': '自动',
    'appearance.autoDesc': '匹配系统主题',
    
    // Business Details Screen
    'businessDetails.title': '企业详情',
    'businessDetails.businessName': '企业名称',
    'businessDetails.taxId': '税号 / EIN',
    'businessDetails.address': '企业地址',
    'businessDetails.industry': '行业',
    'businessDetails.enterBusinessName': '输入企业名称',
    'businessDetails.enterTaxId': '输入税号',
    'businessDetails.enterAddress': '输入企业地址',
    'businessDetails.enterIndustry': '输入行业',
    'businessDetails.saveChanges': '保存更改',
    
    // Contact Support Screen
    'contactSupport.title': '联系支持',
    'contactSupport.email': '电子邮件',
    'contactSupport.liveChat': '在线聊天',
    'contactSupport.available': '可用时间 9am-5pm EST',
    'contactSupport.sendMessage': '给我们发消息',
    'contactSupport.subject': '主题',
    'contactSupport.message': '消息',
    'contactSupport.subjectPlaceholder': '我们能帮您什么？',
    'contactSupport.messagePlaceholder': '描述您的问题或疑问...',
    'contactSupport.submit': '发送消息',
    'contactSupport.missingInfo': '信息缺失',
    'contactSupport.fillAllFields': '请填写所有字段',
    'contactSupport.messageSent': '消息已发送',
    'contactSupport.responseTime': '我们的支持团队将在24小时内回复您',
    
    // Rate App Screen
    'rateApp.title': '评价我们的应用',
    'rateApp.enjoying': '喜欢 Tally 吗？',
    'rateApp.feedbackHelps': '您的反馈帮助我们改进并更好地为您服务',
    'rateApp.amazing': '太棒了！',
    'rateApp.great': '很好！',
    'rateApp.good': '不错',
    'rateApp.fair': '一般',
    'rateApp.poor': '较差',
    'rateApp.helpGrow': '帮助我们成长',
    'rateApp.supportDevelopment': '支持开发',
    'rateApp.shareExperience': '分享您的体验',
    'rateApp.thankYou': '谢谢您！',
    'rateApp.rateAppStore': '您想在 App Store 上给我们评分吗？',
    'rateApp.notNow': '现在不',
    'rateApp.rateButton': '在 App Store 评分',
    'rateApp.feedback': '反馈',
    'rateApp.notSatisfied': '很抱歉您不满意。您想联系支持吗？',
    'rateApp.contactSupport': '联系支持',
    'rateApp.success': '成功',
    'rateApp.thanksSupport': '感谢您的支持！',
    
    // Roles Screen
    'roles.title': '角色',
    'roles.noMembersYet': '还没有成员',
    'roles.emptySubtitle': '添加管理员或员工以管理此组织的访问权限。',
    'roles.admin': '管理员',
    'roles.employee': '员工',
    'roles.created': '创建于',
    'roles.addMember': '添加成员',
    'roles.editEmployee': '编辑员工',
    'roles.deleteMember': '删除成员？',
    'roles.deleteConfirm': '您确定要删除此成员吗？此操作无法撤消。',
    'roles.name': '姓名',
    'roles.email': '电子邮件',
    'roles.role': '角色',
    'roles.employeeNamePlaceholder': '员工姓名',
    'roles.emailPlaceholder': '员工@公司.com',
    'roles.addMemberButton': '添加成员',
    'roles.save': '保存',
  },
};

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
